import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const verb = localFont({
  src: [
    {
      path: "./font/Verb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/Verb-Ultra.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={verb.className}>{children}</body>
    </html>
  );
}
