// Core
import type { Metadata } from "next";

// Global css
import "./globals.css";

// Vendors
import localFont from "next/font/local";

// Global components
import { Layout } from "@/components";

const verb = localFont({
  src: [
    {
      path: "./font/Verb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/Verb-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/Verb-Ultra.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./font/Verb-Ultra.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" sizes="32x32" />
      </head>

      <body className={verb.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
